openapi: 3.0.1
info:
  title: Member
  version: 0.1.0
servers:
- url: "{server}:{port}/member"
  variables:
    server:
      default: http://localhost
    port:
      default: "7099"
paths:
  /match:
    post:
      operationId: postExport
      requestBody:
        content:
          application/fhir+json:
            schema:
              type: object
        required: true
      responses:
        "201":
          description: Created
          content:
            application/fhir+json:
              schema:
                type: object
        "500":
          description: InternalServerError
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
        "400":
          description: BadRequest
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    ErrorPayload:
      required:
      - message
      - method
      - path
      - reason
      - status
      - timestamp
      type: object
      properties:
        timestamp:
          type: string
        status:
          type: integer
          format: int64
        reason:
          type: string
        message:
          type: string
        path:
          type: string
        method:
          type: string
